#!/bin/bash

# CML SETUP


# Lines that begin with #SBATCH specify commands to be used by SLURM for scheduling
#SBATCH --job-name=vits                               # sets the job name if not set from environment
#SBATCH --array=233                   # Submit 8 array jobs, throttling to 4 at a time
#SBATCH --output logs/vits_imgnt1k_cache_hyper_%A_%a.log                            # indicates a file to redirect STDOUT to; %j is the jobid, _%A_%a is array task id
#SBATCH --error logs/vits_imgnt1k_cache_hyper_%A_%a.log                             # indicates a file to redirect STDERR to; %j is the jobid,_%A_%a is array task id
#SBATCH --account=all
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=8
#SBATCH --gpus-per-task=1
#SBATCH --partition=lowpri
#SBATCH --nice=0                                              #positive means lower priority
## SBATCH --dependency=afterany:41100_182                                             #positive means lower priority





module load /data/home/vkhalidov/modulefiles/cuda/11.3
module load /data/home/vkhalidov/modulefiles/nccl/2.12.7-cuda.11.3
module load /data/home/vkhalidov/modulefiles/nccl_efa/1.2.0-nccl.2.12.7-cuda.11.3

export NCCL_NSOCKS_PERTHREAD=4
export NCCL_SOCKET_NTHREADS=2
export NCC_INFO=INFO
export NCCL_SOCKET_IFNAME=ens32

master_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_ADDR=$master_addr
echo "MASTER_ADDR="$master_addr

export MASTER_PORT=$((12000 + $RANDOM % 20000))

source ~/miniconda/etc/profile.d/conda.sh
conda activate ffcv_v2

command_list[0]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.radius_input=0.01 --adv.step_size_input=0.01 --logging.folder output/nomixup_v3/vit_advinput0.01_triple --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[1]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.radius_input=0.02 --adv.step_size_input=0.02 --logging.folder output/nomixup_v3/vit_advinput0.02_triple --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[2]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.radius_input=0.05 --adv.step_size_input=0.05 --logging.folder output/nomixup_v3/vit_advinput0.05_triple --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[3]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.radius_input=0.10 --adv.step_size_input=0.10 --logging.folder output/nomixup_v3/vit_advinput0.10_triple --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[4]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.radius_input=0.20 --adv.step_size_input=0.20 --logging.folder output/nomixup_v3/vit_advinput0.20_triple --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[5]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.radius_input=0.005 --adv.step_size_input=0.005 --logging.folder output/nomixup_v3/vit_advinput0.005_triple --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[6]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.radius_input=0.002 --adv.step_size_input=0.002 --logging.folder output/nomixup_v3/vit_advinput0.002_triple --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[7]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.radius_input=0.001 --adv.step_size_input=0.001 --logging.folder output/nomixup_v3/vit_advinput0.001_triple --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[10]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.double_adv=1 --adv.radius_input=0.01 --adv.step_size_input=0.01 --logging.folder output/nomixup_v3/vit_advinput0.01_triple_dbadv --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[11]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.double_adv=1 --adv.radius_input=0.02 --adv.step_size_input=0.02 --logging.folder output/nomixup_v3/vit_advinput0.02_triple_dbadv --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[12]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.double_adv=1 --adv.radius_input=0.05 --adv.step_size_input=0.05 --logging.folder output/nomixup_v3/vit_advinput0.05_triple_dbadv --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[13]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.double_adv=1 --adv.radius_input=0.10 --adv.step_size_input=0.10 --logging.folder output/nomixup_v3/vit_advinput0.10_triple_dbadv --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[14]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.double_adv=1 --adv.radius_input=0.20 --adv.step_size_input=0.20 --logging.folder output/nomixup_v3/vit_advinput0.20_triple_dbadv --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[15]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.double_adv=1 --adv.radius_input=0.005 --adv.step_size_input=0.005 --logging.folder output/nomixup_v3/vit_advinput0.005_triple_dbadv --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[16]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.double_adv=1 --adv.radius_input=0.002 --adv.step_size_input=0.002 --logging.folder output/nomixup_v3/vit_advinput0.002_triple_dbadv --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[17]="python train_imagenet.py --config-file configs/vit_100cls_advinput_triple.yaml --adv.double_adv=1 --adv.radius_input=0.001 --adv.step_size_input=0.001 --logging.folder output/nomixup_v3/vit_advinput0.001_triple_dbadv --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"


# run multiple finetuning hyperparameter sweep
template="python train_imagenet.py --config-file outputs/nomixup_v3/vit_imagenet100/ab0b15c5-fd26-4fb9-a9c9-6fe01b447b21/params.json"\
" --logging.resume_id=ab0b15c5-fd26-4fb9-a9c9-6fe01b447b21 --logging.resume_checkpoint outputs/nomixup_v3/vit_imagenet100/ab0b15c5-fd26-4fb9-a9c9-6fe01b447b21/epoch299.pt "\
"--dist.multinode=1 --dist.world_size=$SLURM_NTASKS --dist.address=$master_addr --dist.port=$MASTER_PORT --model.arch vit_s_decoupled --adv.adv_loss_weight=0.5 --adv.num_steps=1"\
" --adv.radius_input=0.1 --adv.step_size_input=0.1 --logging.convert=1  --lr.warmup_epochs 0 --data.num_workers=4 "

command_list[20]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.001_ep100_fz10 --lr.lr 0.001 --training.freeze_nonlayernorm_epochs 10 --training.epochs 100 "
command_list[21]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.001_ep100_fz20 --lr.lr 0.001 --training.freeze_nonlayernorm_epochs 20 --training.epochs 100 "
command_list[22]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.001_ep100_fz30 --lr.lr 0.001 --training.freeze_nonlayernorm_epochs 30 --training.epochs 100 "
command_list[23]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.001_ep100_fz50 --lr.lr 0.001 --training.freeze_nonlayernorm_epochs 50 --training.epochs 100 "

command_list[24]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0005_ep100_fz10 --lr.lr 0.0005 --training.freeze_nonlayernorm_epochs 10 --training.epochs 100 "
command_list[25]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0005_ep100_fz20 --lr.lr 0.0005 --training.freeze_nonlayernorm_epochs 20 --training.epochs 100 "
command_list[26]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0005_ep100_fz30 --lr.lr 0.0005 --training.freeze_nonlayernorm_epochs 30 --training.epochs 100 "
command_list[27]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0005_ep100_fz50 --lr.lr 0.0005 --training.freeze_nonlayernorm_epochs 50 --training.epochs 100 "

command_list[28]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0002_ep100_fz10 --lr.lr 0.0002 --training.freeze_nonlayernorm_epochs 10 --training.epochs 100 "
command_list[29]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0002_ep100_fz20 --lr.lr 0.0002 --training.freeze_nonlayernorm_epochs 20 --training.epochs 100 "
command_list[30]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0002_ep100_fz30 --lr.lr 0.0002 --training.freeze_nonlayernorm_epochs 30 --training.epochs 100 "
command_list[31]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0002_ep100_fz50 --lr.lr 0.0002 --training.freeze_nonlayernorm_epochs 50 --training.epochs 100 "

command_list[32]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.001_ep50_fz10 --lr.lr 0.001 --training.freeze_nonlayernorm_epochs 10 --training.epochs 50 "
command_list[33]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.001_ep50_fz20 --lr.lr 0.001 --training.freeze_nonlayernorm_epochs 20 --training.epochs 50 "
command_list[34]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.001_ep50_fz30 --lr.lr 0.001 --training.freeze_nonlayernorm_epochs 30 --training.epochs 50 "

command_list[35]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0005_ep50_fz10 --lr.lr 0.0005 --training.freeze_nonlayernorm_epochs 10 --training.epochs 50 "
command_list[36]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0005_ep50_fz20 --lr.lr 0.0005 --training.freeze_nonlayernorm_epochs 20 --training.epochs 50 "
command_list[37]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0005_ep50_fz30 --lr.lr 0.0005 --training.freeze_nonlayernorm_epochs 30 --training.epochs 50 "

command_list[38]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0002_ep50_fz10 --lr.lr 0.0002 --training.freeze_nonlayernorm_epochs 10 --training.epochs 50 "
command_list[39]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0002_ep50_fz20 --lr.lr 0.0002 --training.freeze_nonlayernorm_epochs 20 --training.epochs 50 "
command_list[40]="$template --logging.folder output_finetune/vit_advinput0.1ft_lr0.0002_ep50_fz30 --lr.lr 0.0002 --training.freeze_nonlayernorm_epochs 30 --training.epochs 50 "

command_list[41]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.001 --adv.step_size_input=0.001 --adv.adv_cache=1 --logging.folder output/nomixup_v3/vit_advinput0.001_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[42]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.002 --adv.step_size_input=0.002 --adv.adv_cache=1 --logging.folder output/nomixup_v3/vit_advinput0.002_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[43]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.005 --adv.step_size_input=0.005 --adv.adv_cache=1 --logging.folder output/nomixup_v3/vit_advinput0.005_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[44]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.010 --adv.step_size_input=0.010 --adv.adv_cache=1 --logging.folder output/nomixup_v3/vit_advinput0.010_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[45]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.020 --adv.step_size_input=0.020 --adv.adv_cache=1 --logging.folder output/nomixup_v3/vit_advinput0.020_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[46]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.050 --adv.step_size_input=0.050 --adv.adv_cache=1 --logging.folder output/nomixup_v3/vit_advinput0.050_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[47]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --logging.folder output/nomixup_v3/vit_advinput0.100_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[50]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.001 --adv.step_size_input=0.001 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.001_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[51]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.002 --adv.step_size_input=0.002 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.002_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[52]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.005 --adv.step_size_input=0.005 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.005_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[53]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.010 --adv.step_size_input=0.010 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[54]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.020 --adv.step_size_input=0.020 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.020_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[55]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.050 --adv.step_size_input=0.050 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.050_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[56]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.100_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[57]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.200 --adv.step_size_input=0.200 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.200_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[58]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --adv.cache_frequency=2  --logging.folder output/nomixup_v3/vit_advinput0.100_decoupled_cache_freq2  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[59]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --adv.cache_frequency=5  --logging.folder output/nomixup_v3/vit_advinput0.100_decoupled_cache_freq5  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[60]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --adv.cache_frequency=10 --logging.folder output/nomixup_v3/vit_advinput0.100_decoupled_cache_freq10 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[61]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --adv.cache_frequency=20 --logging.folder output/nomixup_v3/vit_advinput0.100_decoupled_cache_freq20 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# tweak learning rate
command_list[62]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --lr.lr=0.002 --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --adv.cache_frequency=2  --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_cache_freq2_lr0.002  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[63]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --lr.lr=0.004 --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --adv.cache_frequency=2  --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_cache_freq2_lr0.004  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[64]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --lr.lr=0.006 --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --adv.cache_frequency=2  --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_cache_freq2_lr0.006  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# tweak the cache size of the adversarial filters
command_list[65]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --adv.cache_frequency=2 --adv.cache_size_multiplier=0.5 --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_cache_freq2_cm0.5  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[66]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --adv.cache_frequency=2 --adv.cache_size_multiplier=2   --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_cache_freq2_cm2    --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[67]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.adv_cache=1 --adv.cache_frequency=2 --adv.cache_size_multiplier=4   --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_cache_freq2_cm4    --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test some larger radius
command_list[68]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.200 --adv.step_size_input=0.200 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput0.200_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[69]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.300 --adv.step_size_input=0.300 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput0.300_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[70]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.400 --adv.step_size_input=0.400 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput0.400_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test smaller step sizes at radius 0.1
command_list[71]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.050 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_cache_s0.05 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[72]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.020 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_cache_s0.02 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[73]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.100 --adv.step_size_input=0.010 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_cache_s0.01 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test larger step size
command_list[74]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.500 --adv.step_size_input=0.500 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput0.500_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[75]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.600 --adv.step_size_input=0.600 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput0.600_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[76]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.700 --adv.step_size_input=0.700 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput0.700_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[77]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=0.800 --adv.step_size_input=0.800 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput0.800_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[78]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=1.000 --adv.step_size_input=1.000 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[79]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=1.500 --adv.step_size_input=1.500 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput1.500_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[80]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=2.000 --adv.step_size_input=2.000 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput2.000_decoupled_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[81]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=1.000 --adv.step_size_input=0.500 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.50 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[82]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=1.000 --adv.step_size_input=0.250 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.25 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[83]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=1.000 --adv.step_size_input=0.100 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.10 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[84]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.050 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[85]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=1.000 --adv.step_size_input=0.020 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.020 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[86]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=1.000 --adv.step_size_input=0.010 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.010 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[87]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --training.mixup=0 --training.epochs=300 --adv.radius_input=1.000 --adv.step_size_input=0.005 --adv.adv_cache=1 --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.005 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[90]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.300 --adv.step_size_input=0.015 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.300_decoupled_cache_s0.015 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[91]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.500 --adv.step_size_input=0.025 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.500_decoupled_cache_s0.025 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[92]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput1.000_decoupled_cache_s0.050 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[93]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=1.200 --adv.step_size_input=0.060 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput1.200_decoupled_cache_s0.060 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[94]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=1.500 --adv.step_size_input=0.075 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput1.500_decoupled_cache_s0.075 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[95]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=1.700 --adv.step_size_input=0.085 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput1.700_decoupled_cache_s0.085 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[96]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=2.000 --adv.step_size_input=0.010 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput2.000_decoupled_cache_s0.010 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[97]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.000 --adv.step_size_input=0.00 --adv.num_steps=0 --model.arch=mvit --adv.adv_loss_weight=0 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_baselinev2 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"


command_list[100]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.300 --adv.step_size_input=0.007 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.300_decoupled_cache_s0.007 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[101]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.500 --adv.step_size_input=0.012 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.500_decoupled_cache_s0.012 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[102]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=1.000 --adv.step_size_input=0.025 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput1.000_decoupled_cache_s0.025 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[103]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=1.200 --adv.step_size_input=0.030 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput1.200_decoupled_cache_s0.030 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[104]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=1.500 --adv.step_size_input=0.030 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput1.500_decoupled_cache_s0.030 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[105]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=1.700 --adv.step_size_input=0.040 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput1.700_decoupled_cache_s0.040 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[106]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=2.000 --adv.step_size_input=0.100 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput2.000_decoupled_cache_s0.100 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"


command_list[107]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.0050 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_decoupled_cache_s0.0050 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[108]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.0020 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_decoupled_cache_s0.0020 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[109]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.0010 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_decoupled_cache_s0.0010 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[110]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.0005 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_decoupled_cache_s0.0005 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[111]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.0002 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_decoupled_cache_s0.0002 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[112]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.0100 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_decoupled_cache_s0.0100 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[113]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.2 --adv.step_size_input=0.2000 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.200_decoupled --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[114]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.02 --adv.step_size_input=0.010 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.02_decoupled_cache_s0.010 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[115]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.02 --adv.step_size_input=0.005 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.02_decoupled_cache_s0.005 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[116]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.02 --adv.step_size_input=0.002 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.02_decoupled_cache_s0.002 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[117]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.025 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.025 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[118]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.010 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.010 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[119]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[120]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.10 --adv.step_size_input=0.050 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.10_decoupled_cache_s0.050 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[121]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.10 --adv.step_size_input=0.025 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.10_decoupled_cache_s0.025 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[122]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.10 --adv.step_size_input=0.010 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.10_decoupled_cache_s0.010 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[123]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.000 --adv.step_size_input=0.00 --adv.num_steps=0 --model.arch=mvit --adv.adv_loss_weight=0 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_baselinev3 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[124]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.2 --adv.step_size_input=0.07   --adv.num_steps=3 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.200_decoupled_s0.07sc3 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[125]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.1 --adv.step_size_input=0.04   --adv.num_steps=3 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.100_decoupled_s0.04sc3 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
# understand whether decoupled batchnorm is necessary for using universal perturbation
command_list[126]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.0050 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_cache_s0.0050 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[127]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.0020 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_cache_s0.0020 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[128]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.0010 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_cache_s0.0010 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[129]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.0005 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_cache_s0.0005 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[130]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.0002 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_cache_s0.0002 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test whether class wise universal perturbation is going to be better
command_list[131]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_class_wise=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_classwise --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[132]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.10 --adv.step_size_input=0.010 --adv.adv_cache=1 --adv.cache_class_wise=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.10_decoupled_cache_s0.010_classwise --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[133]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.20 --adv.step_size_input=0.020 --adv.adv_cache=1 --adv.cache_class_wise=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.20_decoupled_cache_s0.020_classwise --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[134]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.30 --adv.step_size_input=0.030 --adv.adv_cache=1 --adv.cache_class_wise=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.30_decoupled_cache_s0.030_classwise --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[135]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.02 --adv.step_size_input=0.002 --adv.adv_cache=1 --adv.cache_class_wise=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.02_decoupled_cache_s0.002_classwise --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test whether memory bank change the loss magnitude
command_list[136]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=2  --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m2  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[137]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m4  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[138]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=8  --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m8  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[139]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=16 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m16 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[140]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=32 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m32 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test whether memory bank change the loss magnitude 
command_list[141]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.07 --adv.step_size_input=0.007 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.07_decoupled_cache_s0.007_m4  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[142]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.10 --adv.step_size_input=0.010 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.10_decoupled_cache_s0.010_m4  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[143]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.15 --adv.step_size_input=0.015 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.15_decoupled_cache_s0.015_m4  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[144]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.20 --adv.step_size_input=0.020 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.20_decoupled_cache_s0.020_m4  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test combination of memory bank and larger step size
command_list[145]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.010 --adv.adv_cache=1 --adv.cache_size_multiplier=2  --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.010_m2  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[146]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.010 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.010_m4  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[147]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.010 --adv.adv_cache=1 --adv.cache_size_multiplier=8  --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.010_m8  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[148]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.010 --adv.adv_cache=1 --adv.cache_size_multiplier=16 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.010_m16 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[149]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.010 --adv.adv_cache=1 --adv.cache_size_multiplier=32 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.010_m32 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test whether updateing the cache sequentially is helpful
command_list[150]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=4 --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m4_seq  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[151]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m4_v2  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[152]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_v2  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test whether using pyramid is helpful
command_list[153]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.01 --adv.step_size_input=0.001 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --adv.pyramid=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.01_decoupled_cache_s0.001_m4_pyramid  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[154]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.02 --adv.step_size_input=0.002 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --adv.pyramid=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.02_decoupled_cache_s0.002_m4_pyramid  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[155]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --adv.pyramid=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m4_pyramid  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[156]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.07 --adv.step_size_input=0.007 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --adv.pyramid=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.07_decoupled_cache_s0.007_m4_pyramid  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[157]="python train_imagenet.py --config-file rn50_configs/rn50_88_epochs_base.yaml --logging.folder outputs/resnet50/rn50_baseline  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[158]="python train_imagenet.py --config-file rn50_configs/rn50_88_epochs_adv.yaml --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=4 --logging.folder outputs/resnet50/rn50_adv0.05_s0.005_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[159]="python train_imagenet.py --config-file rn50_configs/rn50_88_epochs_adv.yaml --adv.radius_input=0.05 --adv.step_size_input=0.025 --adv.num_steps=5 --adv.cache_size_multiplier=4 --logging.folder outputs/resnet50/rn50_adv0.05_s0.025_advprop --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[160]="python train_imagenet.py --config-file rn50_configs/rn50_88_epochs_adv.yaml --adv.radius_input=0.02 --adv.step_size_input=0.002 --adv.adv_cache=1 --adv.cache_size_multiplier=4 --logging.folder outputs/resnet50/rn50_adv0.02_s0.002_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[161]="python train_imagenet.py --config-file rn50_configs/rn50_88_epochs_adv.yaml --adv.radius_input=0.01 --adv.step_size_input=0.001 --adv.adv_cache=1 --adv.cache_size_multiplier=4 --logging.folder outputs/resnet50/rn50_adv0.01_s0.001_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[162]="python train_imagenet.py --config-file rn50_configs/rn50_88_epochs_adv.yaml --adv.radius_input=0.00 --adv.step_size_input=0.000 --adv.adv_cache=1 --adv.cache_size_multiplier=4 --logging.folder outputs/resnet50/rn50_adv0.00_s0.000_cache --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test whether larger radius helps for pyramid
command_list[171]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.10 --adv.step_size_input=0.010 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --adv.pyramid=1 --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.10_decoupled_cache_s0.01_m4_pyramid_seq --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[172]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.20 --adv.step_size_input=0.020 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --adv.pyramid=1 --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.20_decoupled_cache_s0.02_m4_pyramid_seq --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[173]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.30 --adv.step_size_input=0.030 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --adv.pyramid=1 --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.30_decoupled_cache_s0.03_m4_pyramid_seq --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[174]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.50 --adv.step_size_input=0.040 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --adv.pyramid=1 --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.50_decoupled_cache_s0.04_m4_pyramid_seq --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[175]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=1.00 --adv.step_size_input=0.100 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --adv.pyramid=1 --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput1.00_decoupled_cache_s0.10_m4_pyramid_seq --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test whether sequential update brings benefit to other ms
command_list[176]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=6  --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m6_seq  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[177]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=8  --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m8_seq  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[178]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=10 --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m10_seq  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[179]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=16 --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m16_seq  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[180]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=3  --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m3_seq  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[181]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=2  --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m2_seq  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[182]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_size_multiplier=4  --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_m4_seq  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# test whether momentum based adversary is better?
command_list[183]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0 --adv.adv_cache=1 --adv.optimizer=momentum --adv.lr=0.01 --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_momentumlr0.01  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[184]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0 --adv.adv_cache=1 --adv.optimizer=momentum --adv.lr=0.001 --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_momentumlr0.001  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[185]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.05 --adv.step_size_input=0.005 --adv.adv_cache=1 --adv.cache_sequential=1 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.05_decoupled_cache_s0.005_v2  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[190]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.015 --adv.step_size_input=0.006  --adv.num_steps=3 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.015_decoupled_s0.006sc3 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[191]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.010 --adv.step_size_input=0.004  --adv.num_steps=3 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.010_decoupled_s0.004sc3 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[192]="python train_imagenet.py --config-file configs/mvit_decoupled/mvit_100cls_advinput_decoupled.yaml --training.mixup=1 --training.epochs=300 --adv.radius_input=0.020 --adv.step_size_input=0.007  --adv.num_steps=3 --logging.folder outputs/mvit_decoupled_mixup/mvit_imagenet100_advinput0.007_decoupled_s0.007sc3 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

# experiments with resnet50

command_list[193]="python train_imagenet.py --config-file configs/rn50/base.yaml --logging.folder outputs/resnet50/rn50_baseline  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
command_list[194]="python train_imagenet.py --config-file configs/rn50/adv.yaml  --adv.radius_input=$(bc -l <<<'1/(255*0.25)')   --adv.step_size_input=$(bc -l <<<'0.25/(255*0.25)') --adv.adv_loss_even=1 --adv.num_steps=1 --logging.folder outputs/resnet50/rn50_advprop_r1-255s0.25-255c1_evenloss  --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"


# rerunning experiments for vit with cached adversaries
SHARED_PARAM="--training.mixup=0 --training.epochs=300 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
SHARED_PARAM_MIXUP="--training.mixup=1 --training.epochs=300 --data.num_workers=4 --dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"

command_list[200]="python train_imagenet.py --config-file configs/vit_100cls.yaml                                                                                           --logging.project_name vit100 --logging.resume_id=vitaa --logging.folder output/nomixup_v3/ht/vit_baseline $SHARED_PARAM"
command_list[201]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --logging.project_name vit100 --logging.resume_id=vitab --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.05 $SHARED_PARAM"
command_list[202]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=0.100 --adv.step_size_input=0.100 --adv.num_steps=1 --logging.project_name vit100 --logging.resume_id=vitac --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_s0.10c1 $SHARED_PARAM"
command_list[203]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=0.100 --adv.step_size_input=0.050 --adv.num_steps=2 --logging.project_name vit100 --logging.resume_id=vitad --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_s0.05c2 $SHARED_PARAM"
command_list[204]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=0.100 --adv.step_size_input=0.040 --adv.num_steps=3 --logging.project_name vit100 --logging.resume_id=vitae --logging.folder output/nomixup_v3/ht/vit_advinput0.100_decoupled_s0.04c3 $SHARED_PARAM"

command_list[205]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.cache_class_wise=1 --logging.project_name vit100 --logging.resume_id=vitaf --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cacheclasswise_s0.050 $SHARED_PARAM"
command_list[206]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=0.500 --adv.step_size_input=0.025 --adv.adv_cache=1 --adv.cache_class_wise=1 --logging.project_name vit100 --logging.resume_id=vitag --logging.folder output/nomixup_v3/ht/vit_advinput0.500_decoupled_cacheclasswise_s0.025 $SHARED_PARAM"
command_list[207]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=0.250 --adv.step_size_input=0.012 --adv.adv_cache=1 --adv.cache_class_wise=1 --logging.project_name vit100 --logging.resume_id=vitah --logging.folder output/nomixup_v3/ht/vit_advinput0.250_decoupled_cacheclasswise_s0.012 $SHARED_PARAM"

# momentum # will only keep the one with the strongest attack
command_list[208]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.optimizer=momentum --adv.lr=0.1 --logging.project_name vit100 --logging.resume_id=vitai --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.05_momentum0.1 $SHARED_PARAM"
command_list[209]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.optimizer=momentum --adv.lr=0.2 --logging.project_name vit100 --logging.resume_id=vitaj --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.05_momentum0.2 $SHARED_PARAM"
command_list[210]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.optimizer=momentum --adv.lr=0.5 --logging.project_name vit100 --logging.resume_id=vitak --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.05_momentum0.5 $SHARED_PARAM"

command_list[211]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=0.900 --adv.step_size_input=0.045 --adv.adv_cache=1 --adv.cache_class_wise=1 --logging.project_name vit100 --logging.resume_id=vital --logging.folder output/nomixup_v3/ht/vit_advinput0.900_decoupled_cacheclasswise_s0.045 $SHARED_PARAM"


command_list[212]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.optimizer=momentum --adv.lr=1 --logging.project_name vit100 --logging.resume_id=vitam --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.05_momentum1 $SHARED_PARAM"
command_list[213]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.optimizer=momentum --adv.lr=2 --logging.project_name vit100 --logging.resume_id=vitan --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.05_momentum2 $SHARED_PARAM"
command_list[214]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.optimizer=momentum --adv.lr=5 --logging.project_name vit100 --logging.resume_id=vitao --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.05_momentum5 $SHARED_PARAM"

command_list[215]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.optimizer=momentum --adv.lr=100 --logging.project_name vit100 --logging.resume_id=vitap --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.05_momentum100 $SHARED_PARAM"
command_list[216]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.optimizer=momentum --adv.lr=1000 --logging.project_name vit100 --logging.resume_id=vitaq --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.05_momentum1000 $SHARED_PARAM"
command_list[217]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.optimizer=momentum --adv.lr=10000 --logging.project_name vit100 --logging.resume_id=vitar --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cache_s0.05_momentum10000 $SHARED_PARAM"

command_list[218]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.radius_schedule=1 --adv.max_radius_multiplier=2 --adv.start_epoch=30 --logging.project_name vit100 --logging.resume_id=vitas --logging.folder output/nomixup_v3/ht/vit_advinput1.000-2-at-ep30_decoupled_cache_s0.05 $SHARED_PARAM"
# shuffling the adversary to prevent for overfitting
command_list[219]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.cache_class_wise=1 --adv.cache_class_wise_shuffle_iter=50 --logging.project_name vit100 --logging.resume_id=vitat --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cacheclasswiseshuffle50_s0.050 $SHARED_PARAM"

#other hyperparameter for epsilon scheduling
command_list[220]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.radius_schedule=1 --adv.max_radius_multiplier=2.5 --adv.start_epoch=30 --logging.project_name vit100 --logging.resume_id=vitau --logging.folder output/nomixup_v3/ht/vit_advinput1.000-2.5-at-ep30_decoupled_cache_s0.05 $SHARED_PARAM"
command_list[221]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.radius_schedule=1 --adv.max_radius_multiplier=1.5 --adv.start_epoch=30 --logging.project_name vit100 --logging.resume_id=vitav --logging.folder output/nomixup_v3/ht/vit_advinput1.000-1.5-at-ep30_decoupled_cache_s0.05 $SHARED_PARAM"

command_list[222]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.cache_class_wise=1 --adv.cache_class_wise_shuffle_iter=100 --logging.project_name vit100 --logging.resume_id=vitaw --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cacheclasswiseshuffle100_s0.050 $SHARED_PARAM"
command_list[223]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.cache_class_wise=1 --adv.cache_class_wise_shuffle_iter=200 --logging.project_name vit100 --logging.resume_id=vitax --logging.folder output/nomixup_v3/ht/vit_advinput1.000_decoupled_cacheclasswiseshuffle200_s0.050 $SHARED_PARAM"

# testing variations of epsilon schedules
command_list[224]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.radius_schedule=1 --radius.min_multiplier=0 --radius.start_epoch=30 --radius.schedule_type=linear_decrease                                         --logging.project_name vit100 --logging.resume_id=vitba --logging.folder output/nomixup_v3/ht/vit_advinput1.000-0.1-at-ep30_decoupled_cache_s0.05 $SHARED_PARAM"
command_list[225]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.radius_schedule=1 --radius.max_multiplier=2 --radius.min_multiplier=0 --radius.period_count=5 --radius.start_epoch=30 --radius.schedule_type=wave  --logging.project_name vit100 --logging.resume_id=vitbb --logging.folder output/nomixup_v3/ht/vit_advinput1.000-wave-p5-max2-min0-at-ep30_decoupled_cache_s0.05 $SHARED_PARAM"
command_list[226]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.radius_schedule=1 --radius.max_multiplier=2 --radius.min_multiplier=0 --radius.period_count=3 --radius.start_epoch=30 --radius.schedule_type=wave  --logging.project_name vit100 --logging.resume_id=vitbc --logging.folder output/nomixup_v3/ht/vit_advinput1.000-wave-p3-max2-min0-at-ep30_decoupled_cache_s0.05 $SHARED_PARAM"
command_list[227]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.radius_schedule=1 --radius.max_multiplier=2 --radius.min_multiplier=0 --radius.period_count=2 --radius.start_epoch=30 --radius.schedule_type=wave  --logging.project_name vit100 --logging.resume_id=vitbd --logging.folder output/nomixup_v3/ht/vit_advinput1.000-wave-p2-max2-min0-at-ep30_decoupled_cache_s0.05 $SHARED_PARAM"

command_list[228]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.radius_schedule=1 --radius.max_multiplier=2   --radius.min_multiplier=0   --radius.period_count=5 --radius.start_epoch=30 --radius.schedule_type=teeth                            --logging.project_name vit100 --logging.resume_id=vitbe --logging.folder output/nomixup_v3/ht/vit_advinput1.000-teeth-p5-max2-min0-at-ep30_decoupled_cache_s0.05 $SHARED_PARAM"
command_list[229]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.radius_schedule=1 --radius.max_multiplier=2   --radius.min_multiplier=0   --radius.period_count=5 --radius.start_epoch=30 --radius.schedule_type=teeth --radius.reset_layernorm=1 --logging.project_name vit100 --logging.resume_id=vitbf --logging.folder output/nomixup_v3/ht/vit_advinput1.000-teeth-reln-p5-max2-min0-at-ep30_decoupled_cache_s0.05 $SHARED_PARAM"
command_list[230]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.radius_schedule=1 --radius.max_multiplier=1.5 --radius.min_multiplier=0.5 --radius.period_count=5 --radius.start_epoch=30 --radius.schedule_type=wave                             --logging.project_name vit100 --logging.resume_id=vitbg --logging.folder output/nomixup_v3/ht/vit_advinput1.000-wave-p5-max1.5-min0.5-at-ep30_decoupled_cache_s0.05 $SHARED_PARAM"
command_list[231]="python train_imagenet.py --config-file configs/vit_100cls_advinput_decoupled.yaml --adv.radius_input=1.000 --adv.step_size_input=0.050 --adv.adv_cache=1 --adv.radius_schedule=1 --radius.max_multiplier=2   --radius.min_multiplier=0   --radius.period_count=10 --radius.start_epoch=30 --radius.schedule_type=teeth --radius.reset_layernorm=1 --logging.project_name vit100 --logging.resume_id=vitbh --logging.folder output/nomixup_v3/ht/vit_advinput1.000-teeth-reln-p10-max2-min0-at-ep30_decoupled_cache_s0.05 $SHARED_PARAM"

# testing simple vit with randaug + mixup
SHARED_PARAM="--dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr"
PYRAMID_PARAM="--training.mixup=1 --training.randaug=1 --training.randaug_num_ops=2 --training.randaug_magnitude=10 --training.mixed_precision=0 --lr.warmup_epochs=4 --model.arch=vit_s"
command_list[232]="python train_imagenet.py --config-file configs/pyramid/vitb_1000cls.yaml $PYRAMID_PARAM                                                                                                                                         --logging.project_name imgnt1K --logging.resume_id=vits1000epoch300arv3 --logging.folder output/pyramid/simplevits_baseline $SHARED_PARAM"

# testing simple vit with randaug + mixup without label smoothing
SHARED_PARAM="--dist.world_size=$SLURM_NTASKS --dist.multinode=1 --dist.port=$MASTER_PORT --dist.address=$master_addr --training.label_smoothing=0"
PYRAMID_PARAM="--training.mixup=1 --training.randaug=1 --training.randaug_num_ops=2 --training.randaug_magnitude=10 --training.mixed_precision=0 --lr.warmup_epochs=4 --model.arch=vit_s"
command_list[233]="python train_imagenet.py --config-file configs/pyramid/vitb_1000cls.yaml $PYRAMID_PARAM                                                                                                                                         --logging.project_name imgnt1K --logging.resume_id=vits1000epoch300asv3 --logging.folder output/pyramid/simplevits_baseline_nosmooth $SHARED_PARAM"

cur_command=${command_list[SLURM_ARRAY_TASK_ID]}
echo $cur_command
eval "srun -n $SLURM_NTASKS $cur_command"