data:
  in_memory: 1
  num_workers: 4
  num_classes: 1000
  train_dataset: /data/home/pingchiang/data/imagenet_ffcv/train_500_0.50_90.ffcv
  val_dataset: /data/home/pingchiang/data/imagenet_ffcv/val_500_0.50_90.ffcv
dist:
  world_size: 8
logging:
  folder: /tmp/
lr:
  lr: 0.1
  lr_schedule_type: step_fastadvprop
  step_ratio: 0.1
model:
  arch: resnet50_decoupled
resolution:
  end_ramp: 76
  max_res: 224
  min_res: 224
  start_ramp: 65
training:
  batch_size: 64
  bn_wd: 0
  distributed: 1
  epochs: 105
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
  use_blurpool: 0
validation:
  lr_tta: 0
  resolution: 256
adv:
  radius_input: 1.0
  step_size_input: 0.25
  num_steps: 5
  split_backward: 1
  adv_loss_weight: 0.5
