data:
  in_memory: 1
  num_workers: 4
  num_classes: 1000
  train_dataset: /data/home/pingchiang/data/imagenet_ffcv/train_500_0.50_90.ffcv
  val_dataset: /data/home/pingchiang/data/imagenet_ffcv/val_500_0.50_90.ffcv
dist:
  world_size: 8
logging:
  folder: ./outputs/mvitb/baseline
  log_level: 2
lr:
  lr: 0.002
  lr_schedule_type: cyclic_warm
  warmup_epochs: 70
model:
  arch: mvit_s
resolution:
  end_ramp: 13
  max_res: 224
  min_res: 224
  start_ramp: 11
training:
  batch_size: 128
  bn_wd: 0
  distributed: 1
  epochs: 300
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: adamw
  grad_clip_norm: 1.0
  weight_decay: 0.05
  use_blurpool: 1
  mixup: 1
validation:
  batch_size: 64
  lr_tta: true
  resolution: 224
